-- Users feature: User and UserProfile

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255)             NOT NULL,
    phone_number VARCHAR(32),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number),
    CONSTRAINT ck_users_email_lowercase CHECK (email = LOWER(email))
);

CREATE TABLE user_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL,
    display_name VARCHAR(50)              NOT NULL,
    avatar_url   VARCHAR(2048),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
