-- Calendar feature. Depends on the users table from V1 (user module).

CREATE TABLE calendars (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_calendars_owner UNIQUE (owner_id),
    CONSTRAINT fk_calendars_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Names are unique per owner (case-insensitive, via name_key). Colours are unique per owner
-- except the default grey #9E9E9E, whose color_key is NULL (NULLs never conflict).
CREATE TABLE categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                   NOT NULL,
    name       VARCHAR(50)              NOT NULL,
    name_key   VARCHAR(50)              NOT NULL,
    color      VARCHAR(7)               NOT NULL,
    color_key  VARCHAR(7),
    is_default BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_categories_owner_name UNIQUE (owner_id, name_key),
    CONSTRAINT uk_categories_owner_color UNIQUE (owner_id, color_key),
    CONSTRAINT ck_categories_color_key CHECK (
        (color = '#9E9E9E' AND color_key IS NULL) OR (color <> '#9E9E9E' AND color_key IS NOT NULL AND color_key = color)),
    CONSTRAINT ck_categories_default_grey CHECK (is_default = FALSE OR color = '#9E9E9E'),
    CONSTRAINT fk_categories_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id BIGINT                   NOT NULL,
    category_id BIGINT                   NOT NULL,
    created_by  BIGINT                   NOT NULL,
    name        VARCHAR(100)             NOT NULL,
    note        VARCHAR(1000),
    start_at    TIMESTAMP                NOT NULL,
    end_at      TIMESTAMP                NOT NULL,
    all_day     BOOLEAN                  NOT NULL DEFAULT FALSE,
    time_zone   VARCHAR(64)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_events_end_after_start CHECK (end_at > start_at),
    CONSTRAINT fk_events_calendar FOREIGN KEY (calendar_id) REFERENCES calendars (id) ON DELETE CASCADE,
    CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_events_calendar_start ON events (calendar_id, start_at);

CREATE TABLE event_recurrences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT      NOT NULL,
    frequency       VARCHAR(10) NOT NULL,
    repeat_interval INTEGER     NOT NULL DEFAULT 1,
    until_date      DATE,
    CONSTRAINT uk_event_recurrences_event UNIQUE (event_id),
    CONSTRAINT ck_event_recurrences_frequency CHECK (frequency IN ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'CUSTOM')),
    CONSTRAINT ck_event_recurrences_interval CHECK (repeat_interval >= 1),
    CONSTRAINT fk_event_recurrences_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE event_recurrence_days (
    recurrence_id BIGINT     NOT NULL,
    day_of_week   VARCHAR(9) NOT NULL,
    CONSTRAINT pk_event_recurrence_days PRIMARY KEY (recurrence_id, day_of_week),
    CONSTRAINT ck_event_recurrence_days_day CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT fk_event_recurrence_days_recurrence FOREIGN KEY (recurrence_id)
        REFERENCES event_recurrences (id) ON DELETE CASCADE
);

CREATE TABLE event_exceptions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT       NOT NULL,
    occurrence_date DATE         NOT NULL,
    cancelled       BOOLEAN      NOT NULL DEFAULT FALSE,
    name            VARCHAR(100),
    start_at        TIMESTAMP,
    end_at          TIMESTAMP,
    category_id     BIGINT,
    CONSTRAINT uk_event_exceptions_event_date UNIQUE (event_id, occurrence_date),
    CONSTRAINT fk_event_exceptions_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_exceptions_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE calendar_permissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id  BIGINT                   NOT NULL,
    user_id      BIGINT                   NOT NULL,
    access_level VARCHAR(10)              NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_calendar_permissions_calendar_user UNIQUE (calendar_id, user_id),
    CONSTRAINT ck_calendar_permissions_access CHECK (access_level IN ('READ_ONLY', 'READ_WRITE')),
    CONSTRAINT fk_calendar_permissions_calendar FOREIGN KEY (calendar_id) REFERENCES calendars (id) ON DELETE CASCADE,
    CONSTRAINT fk_calendar_permissions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_calendar_permissions_user ON calendar_permissions (user_id);

CREATE TABLE calendar_invites (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id     BIGINT                   NOT NULL,
    inviter_id      BIGINT                   NOT NULL,
    invitee_contact VARCHAR(255)             NOT NULL,
    token           VARCHAR(64)              NOT NULL,
    access_level    VARCHAR(10)              NOT NULL,
    status          VARCHAR(10)              NOT NULL,
    expires_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_calendar_invites_token UNIQUE (token),
    CONSTRAINT ck_calendar_invites_access CHECK (access_level IN ('READ_ONLY', 'READ_WRITE')),
    CONSTRAINT ck_calendar_invites_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')),
    CONSTRAINT fk_calendar_invites_calendar FOREIGN KEY (calendar_id) REFERENCES calendars (id) ON DELETE CASCADE,
    CONSTRAINT fk_calendar_invites_inviter FOREIGN KEY (inviter_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_calendar_invites_calendar_status ON calendar_invites (calendar_id, status);
